modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/Akkiruk/cobblemon-spawning-rei/issues"

[[mods]]
modId="cobbledex_rei_emi_jei"
version="${version}"
displayName="CobbleDex REI/EMI/JEI"
description='''Your complete Cobblemon Pokédex in REI, JEI, or EMI. Browse spawn locations, evolution chains, base stats, item drops, Pokédex info, and special obtainment methods for every Pokémon — all from your recipe viewer.'''
authors="Akkiruk"
logoFile="assets/cobbledex-rei-emi-jei/icon.png"
displayURL="https://github.com/Akkiruk/cobblemon-spawning-rei"

[[dependencies.cobbledex_rei_emi_jei]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="CLIENT"

[[dependencies.cobbledex_rei_emi_jei]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="CLIENT"

[[dependencies.cobbledex_rei_emi_jei]]
modId="cobblemon"
type="required"
versionRange="[1.7.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.cobbledex_rei_emi_jei]]
modId="kotlinforforge"
type="required"
versionRange="[5.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.cobbledex_rei_emi_jei]]
modId="roughlyenoughitems"
type="optional"
versionRange="[16.0,)"
ordering="NONE"
side="CLIENT"
