modLoader="kotlinforforge"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/Akkiruk/cobblemon-spawning-rei/issues"

[[mods]]
modId="cobblemon_spawning_rei"
version="${version}"
displayName="Cobblemon Spawning REI Integration"
description='''Adds Cobblemon spawn locations, evolution chains, and species info to REI. Search any Pokémon to see where it spawns, how it evolves, and what conditions are needed.'''
authors="Akkiruk"
displayURL="https://github.com/Akkiruk/cobblemon-spawning-rei"

[[dependencies.cobblemon_spawning_rei]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_spawning_rei]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_spawning_rei]]
modId="cobblemon"
type="required"
versionRange="[1.7.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cobblemon_spawning_rei]]
modId="kotlinforforge"
type="required"
versionRange="[5.0.0,)"
ordering="NONE"
side="BOTH"
